### ISSUE TITLE
Only sport+ livestream available

### ISSUE THREAD

**Issue by dertobias** [s0faking/plugin.video.orftvthek#104]
Since latest update there‘s only orf sport+ as livestream available. I checkt with the browser and orf1 and 2 livestream should also be there...
Otherwise a great plugin and thanks for developing and maintaining!!
Cheers
Tobi

**Comment by s0faking** [comment]
whats the selected quality on your settings page? do you have "inputstream adaptive" installed? the drm streams can only be played if inputstream adaptive is installed. also you might want to change the quality to adaptive if it isnt already. i've just pushed a new commit that handles the quality selection much better. you can also try that out if you want, but there is only a matrix version (devel branch) yet.

**Comment by dertobias** [comment]
just changed it from HD to adaptiv, but there's still one sport+ available :-/

**Comment by s0faking** [comment]
Can you post a debug log? What KODi Version are you using?

**Comment by dertobias** [comment]
just installed InputStream Adaptive. now i can see other livestreams, but those won't play...
i got CoreElec 9.2.7 on an Odroid C4, cant find kodi infos

**Comment by dertobias** [comment]
updatetet my c4 to the latest coreelec 19.1 Matrix.
Tried to start an orf3 livestream, after that it forced me to install widevine (chorme recorvery)and now it streams just fine, at least orf 3 and sport +(the only one available atm).  Never heard of widevine - is it save to use?

**Comment by s0faking** [comment]
yes of course. widevine is the drm technology. its a very common format, and most of the big broadcast companies are using this. the inputstream helper addon handles that stuff (for example the prompt to install widevine). i will try to add a few instructions to the readme file for the requirements to see all active livestreams.

**Comment by dertobias** [comment]
many thx and enjoy the rest of sunday :)
