### ISSUE TITLE
Livestream not working due to DRM being required

### ISSUE THREAD

**Issue by azrinyi** [s0faking/plugin.video.orftvthek#105]
I'm using LibreELEC 9.2.7 which still uses Kodi 18.4 and not the new Matrix release. While there is a BETA release of LibreELEC 10 using Matrix available, it is currently not recommended to use it.

At the moment, I get a DRM warning when I try to watch the Livestreams of ORF1 and ORF2 on 0.12. According to the release page DRM Livestream capabilities have been added to 0.12.1+matrix.1. Do you intend to add this feature to 0.12 as well?

**Comment by flashkiller999** [comment]
Hello,

problem is not a problem only pertaining to Kodi 18.4, but also Kodi 19.1 (Matrix).
I installed the newest Addon 0.12.1+matrix.1 and encounter the same problem on Kodi 19.1.
Interestingly enough only ORF 1 & 2 have this problem ORF III does work, so it seems that this new DRM-setup only covers ORF 1&2. 

I hope that this will be solved soon.

Cheers
Paul

**Comment by flashkiller999** [comment]
Same problem with Kodi 19.1 and Addon version 0.12.1+matrix.1

Only occurs for ORF 1 & 2, ORF III does still work.

**Comment by Schaussi** [comment]
Same here (LE 9.2.6), since today. Completed (past) streams of the program work, livestreams show a DRM error.
It seems there was a server-sided change during last night. Kodinerds' IPTV ORF links (to be used with Tvheadend or Iptvsimpleclient addon) also do not work any more.
Using Zappn addon for ORF livestream for the moment - non-HD unfortunately, but working fine also today.

**Comment by s0faking** [comment]
thx for reporting the issue. i will look into it. probably some drm related changes right before the em i guess.

**Comment by s0faking** [comment]
its fixed with 0.12.2. at least for matrix. i will fix the master (<19) repo tomorrow.

**Comment by Franz47** [comment]
> Using Zappn addon for ORF livestream for the moment - non-HD unfortunately, but working fine also today.

Many thanks for communicating this idea. Works well enough to watch live evening news in the garden, where a Raspberry Pi2 works as media center.

**Comment by s0faking** [comment]
i've also added a non matrix version to the release page. you can install the zip file for now. i recommend to disable the service api , i will have to adapt everything to the newest api version in order to fully support drm. also restart is only working on matrix.

**Comment by azrinyi** [comment]
Thanks, it works now again!

**Comment by Franz47** [comment]
Thanks, on my Pi everything works fine again without updating Windevine.

**Comment by UserX404** [comment]
Hi
Is restart of a life stream working for you?

**Comment by s0faking** [comment]
works on my end. can you open a new issue and provide some debug logs?
