### ISSUE TITLE
FEATURE REQUEST: Support for new UHD DRM Streams

### ISSUE THREAD

**Issue by likeadoc** [s0faking/plugin.video.orftvthek#106]
For the UEFA EURO 2020 (2021) the ORF decided to implement DRM Streams for all broadcasted games. This is also true for the UHD streams located here 

[DASH]
https://orfuhd.mdn.ors.at/out/u/orfuhd/drmhdr10b/manifest.mpd (Android TV) quality_key: UHDANDROIDTV
https://orfuhd.mdn.ors.at/out/u/orfuhd/drmhdr10a/manifest.mpd (Browser) quality_key: UHDBrowser
https://orfuhd.mdn.ors.at/out/u/orfuhd/drmhdr10/manifest.mpd (SmartTV) quality_key: UHDSMARTV

[HLS]
https://orfuhd.mdn.ors.at/out/u/orfuhd/drmhdr10b/manifest.m3u8 (AppleTV)
https://orfuhd.mdn.ors.at/out/u/orfuhd/drmhdr10b/manifest1.m3u8 (Browser)
 

Provided the DASH streams are Widevine L3 compatible streams -  would it be possible to add support for those?

Cheers

**Comment by likeadoc** [comment]
After further testing it seems those streams are indeeed Widevine L3 compatible and should be relatively trivial to implement.

**Comment by s0faking** [comment]
works with 0.12.2+matrix from the release page. for now uhd is only available when serviceapi is off

**Comment by likeadoc** [comment]
I am working on implementing it through the serviceapi atm :)

**Comment by likeadoc** [comment]
it seems that https://orfuhd.mdn.ors.at/out/u/orfuhd/drmhdr10a/manifest.mpd (Browser) quality_key: UHDBrowser is 8bit non hdr content btw

**Comment by likeadoc** [comment]
https://orfuhd.mdn.ors.at/out/u/orfuhd/drmhdr10a/manifest.mpd (Browser) quality_key: UHDBrowser seems to be HEVC Main Profile - i.e. 8 bit

**Comment by JesusMcCloud** [comment]
Not sure id this issue is just referencing livestreams, but when I try to re-watch a game I only get the short clip informing me of lacking DRM support.
I'm on LE 9.5.4 on an RPi4, tried releases and devel branch

**Comment by s0faking** [comment]
yes drm is also enabled for a few archived videos. for now it looks like only EM footage is DRM only. i've added a few changes to the matrix version to support those videos.

**Comment by s0faking** [comment]
i've updated the matrix zip from the release page. uhd streams are now also working with the serviceapi

**Comment by s0faking** [comment]
> https://orfuhd.mdn.ors.at/out/u/orfuhd/drmhdr10a/manifest.mpd (Browser) quality_key: UHDBrowser seems to be HEVC Main Profile - i.e. 8 bit

i've checked a sample file from the uhd stream. its not uhd at all. i'm getting 720p :(

`Stream #0:0(und): Video: hevc (hev1 / 0x31766568), none, 1280x720, 50 tbr, 50 tbn, 50 tbc (default)`

**Comment by likeadoc** [comment]
@s0faking all of the aforementioned streams are adaptive streams
https://orfuhd.mdn.ors.at/out/u/orfuhd/drmhdr10b/manifest.mpd (Android TV) quality_key: UHDANDROIDTV 1280x720 - 2560x1440 HEVC 10bit HDR 
https://orfuhd.mdn.ors.at/out/u/orfuhd/drmhdr10a/manifest.mpd (Browser) quality_key: UHDBrowser 1280x720 - 3840x2160 HEVC 8bit SDR
https://orfuhd.mdn.ors.at/out/u/orfuhd/drmhdr10/manifest.mpd (SmartTV) quality_key: UHDSMARTV 1280x720 - 3840x2160 HEVC 10bit HDR

**Comment by s0faking** [comment]
Thx @likeadoc

**Comment by s0faking** [comment]
i pushed the changes to the official repo today
