### ISSUE TITLE
[Feature Request] direct URI for simple IPTV

### ISSUE THREAD

**Issue by bananenfisch** [s0faking/plugin.video.orftvthek#108]
Hi,

thanks a lot for this plugin, also now working with widevine!
Is it possible with these license checking to provide an plugin URI to start the a live stream directly? Sometimes i just use simple IPTV and some plugins work with m3u lists, like zappn:

`#EXTINF:-1 tvg-name="orf1" tvg-id="ORF1.at" group-title="zappn-AT",orf1`
`plugin://plugin.video.zappntv/category/livestream/orf1`

... watching on the log i see different keys/ids/etc. to get this working... so i don't know if it's possible to get a static URI, which will start all these license jobs after request?

If it's easy to implement or... is there already a way to get this working? :-)
Thanks!

**Comment by babsi0995** [comment]
Yes I agree this would really be a great feature ti get ORF in HD! I also use the static URLs of zappn and use the PVR manager simple iptv. 
FYI: For ORF I noticed that the local streams (e.g. ORF OÖ) and ORF 3 are not encrypted and you can add the stream URLs to your PVR manager

**Comment by s0faking** [comment]
i will look into it when i have a little spare time. didn't know pvr was able to link plugin handles. atm this won't work because the drm infos needed to decrypt the stream are added the listitem on directory listings.

**Comment by gsantner** [comment]
Is there something new since last year?    Also have plugin://zappn in the stream m3u playlist and unfortunatley cannot find a counterpart in this ORF specific addon.

**Comment by s0faking** [comment]
add the channels like this

```
#EXTINF:-1 tvg-name="ORF 1" tvg-id="ORF 1" group-title="ORF",orf1
plugin://plugin.video.orftvthek/?channel=orf1&mode=pvr

#EXTINF:-1 tvg-name="ORF 2" tvg-id="ORF 2" group-title="ORF",orf2
plugin://plugin.video.orftvthek/?channel=orf2&mode=pvr

#EXTINF:-1 tvg-name="ORF 3" tvg-id="ORF 3" group-title="ORF",orf3
plugin://plugin.video.orftvthek/?channel=orf3&mode=pvr

#EXTINF:-1 tvg-name="ORF Sport+" tvg-id="ORF Sport+" group-title="ORF",orfs
plugin://plugin.video.orftvthek/?channel=orfs&mode=pvr

```

works only with service api for now. i will add htmlscraper support in another commit

**Comment by gsantner** [comment]
@s0faking  
Thank you for coming back to it!  

I tried it with latest git version. At first looked like it's not working, but then read again about "service api" as didn't know what it is about. After discovering the settings options at the ORF addon and enabling that, it worked just fine.

So replaced the broken 3 Zappn plugin:// links with the orftvthek links and it works fine from IPTV Simple 😄 .  
Really nice that Kodi is quite open here and you can quite easy integrate videos & streams from kinda any source just like it would be a normal TV channel.

**Comment by s0faking** [comment]
should work with the htmlscraper as well with the last commit. i've also added uhd streams (if available) and the bundesland orf versions. infos on how to add them are in the README.md.

**Comment by gsantner** [comment]
does orf2K for example only work during ZIB times or all the time? At last before where a simple single URL was enough, the regional streams only worked during ZIB and for the rest of time normal ORF2 had to be used

**Comment by s0faking** [comment]
Regional streams fallback to ORF 2 if Bundesland heute is not on. You might need to restart the Stream though
