### ISSUE TITLE
Videoauflösung im Konfig-Menu ohne Funktion / generell nur noch HD seit 6.12.2021?

### ISSUE THREAD

**Issue by Walker7401** [s0faking/plugin.video.orftvthek#116]
Hi,
bereits in den letzten Tagen ist mir aufgefallen, dass die Videoqualitätseinstellung im Menü offenbar ignoriert wird. Mein Setting ist niedrig, da unser Magenta-LTE Internet leider nichts leistet.
Klappte bisher tadellos, doch seit ca 2 Wochen wird die Einstellung ignoriert.
Der Stream startet IMMER mit maximaler Bandbreits (ie. HD) - wenn er denn überhaupt startet.
Seit heute (6.12.2021) startet nur noch ORF 3 (das keiner braucht), alle anderen Streams starten nicht (Fehlermeldung, manchmal: Stream konnte nicht gestartet werden).
Über Chrome und dem Web-Player sind alle Auflösungen (also die niedrigen, leider) wählbar und spielen auch.
Woran liegt das? Am ORF? An Google (WideVine)?
System: QNAP, 8GB RAM, direkt via Gigabit am LTE Router, Kodi Matrix 19.3., fresh install

**Comment by s0faking** [comment]
die quality settings gibts mit der neusten version 0.12.3-1 gar nicht mehr (die streams wurden schon länger vom orf eingestellt). du musst - falls du noch eine ältere version installiert hast - "adaptive" auswählen. dann sollte sich die qualität an deine bandbreite anpassen. zur not kannst du in den video settings auch eine stream qualität auswählen, das musst du aber bei "inputstream adaptive" vorher einstellen ("stream auswahl")

**Comment by killerbees19** [comment]
> die streams wurden schon länger vom orf eingestellt

Kleine Ergänzung, da es Andere vielleicht interessiert: Das trifft nur für `orf1` und `orf2` (exkl. Regionalprogramme) zu! Bei allen anderen Streams gibt es `q4a`, `q6a` und `q8c` nach wie vor. Nur `q1a` wurde vor einiger Zeit komplett gestrichen.

Deshalb funktioniert der Stream von `orf3` auch noch mit einer anderen Qualitätseinstellung 🤓
