### ISSUE TITLE
Settings für schlechtes Internet

### ISSUE THREAD

**Issue by HinzundKunz** [s0faking/plugin.video.orftvthek#117]
Wir leben in Afrika, wo das Internet chronisch schlecht ist (mobiles Internet mit zu vielen Nutzern, also kurze Abschnitte mit schnellem Internet, dann längere Pausen ohne Fortschritt). Das TVthek plugin buffert zu wenig Video, sodass es immer hängen bleibt. Wäre es möglich, die Zwischenspeicherung zu erhöhen, um Vorladen zu ermöglichen?

**Comment by killerbees19** [comment]
Ich habe das selbst noch nie gebraucht, aber schau Dir mal folgende Wikiartikel an:

* https://kodi.wiki/view/HOW-TO:Modify_the_video_cache
* https://kodi.wiki/view/Advancedsettings.xml#cache

Vielleicht hilft das schon?

**Comment by HinzundKunz** [comment]
Hab ich schon, hilft leider nicht wirklich. Allerdings bin ich gestern drauf gekommen, dass das Problem nicht auf dein Plugin beschränkt ist, sondern auch in Youtube auftritt. Ist also ein allgemeines Problem, evtl auf meinem libreelec. Ich schließ den issue mal. Danke für deine Antwort!
