### ISSUE TITLE
No live video ORF1,2,3 - licence key error

### ISSUE THREAD

**Issue by Walker7401** [s0faking/plugin.video.orftvthek#118]
Hi,
as of yesterday live video fails. Log says: Input stream adaptive initialize failed, error opening, license update not successul (no keys), license server returned failure

Seems there was a change at ORF?
System: QNAP 251+, linux ubuntu 18.04.5 LTS,  Kodi 19.3.0 (20211029), orftvthek 0.12.3+matrix.1

**Comment by s0faking** [comment]
looks like they changed something with the user token. i will look into it

**Comment by UserX404** [comment]
'Restart' isn't working and 'Live' is mega laggy.

**Comment by UserX404** [comment]
@s0faking
Die andern Streams (Neueste Sendungen) scheinen auch Probleme zu haben und reißen ständig ab.
Hast du das Problem nachstellen  können?

**Comment by s0faking** [comment]
the restart option works for me except for drm content. havent had any problems with the normal videos please send me a debug log if you can. might be just a network issue with the amazon servers i guess. 

as for the drm problem i'm not 100% sure yet but it looks like theres a widevine issue. the license request returns error 500. i will post this issue on the inputstream.adaptive issues page, maybe they know whats going on. 

```2022-01-27 00:00:32.578 T:11580   DEBUG <general>: Curl::Debug - TEXT: Connection #0 to host drm.ors.at left intact
2022-01-27 00:00:32.578 T:11580   ERROR <general>: CCurlFile::Open failed with code 500 for https://drm.ors.at/acquire-license/widevine?BrandGuid=13f2e056-53fe-4469-ba6d-999970dbe549&userToken=CLzwYDsNYJARVCNiGuBiLbkE7ac140yZ9JvCzRVzUSH%2B0AQAQtcKWxGz0%2BhmXiwvy8tVGY3eWqFXuObrLo%2FCXKI2e9JqacwT9MZToGDzfe1RB0ZddK6bYwUM8CLL7yfrGxFiBdJCjjiitWUTk%2B8WkqphXdjg7UB%2BZUbKcU8GvFW4xIRAOZUZVXdpm9cqO18%2BPEXM65DmcCbg7h3PVa%2FXcriL8F80NrH%2F8BzwkplMiEd5e3T3qBorUaGx65yxVah%2B:
                                                   
2022-01-27 00:00:32.578 T:11580   ERROR <general>: AddOnLog: inputstream.adaptive: License server returned failure
2022-01-27 00:00:32.578 T:11580   ERROR <general>: AddOnLog: inputstream.adaptive: License update not successful (no keys)```

**Comment by s0faking** [comment]
i think i fixed the issue. drm content is working again with this commit. probably needs some further testing but it's looking good so far

**Comment by UserX404** [comment]
Thank you for your work.
I see the new 0.12.4 matrix release.
Is there also a release for Leia?
I'm running on Libreelec on RPi4 and want to wait for the next stable release before switching.

**Comment by s0faking** [comment]
i've added a non matrix version to the release page. unfortunately i can't test this right now but i think i should work

**Comment by UserX404** [comment]
Will report back when tested.

**Comment by UserX404** [comment]
Just tested running the ZIB2 live stream. I keeps stuttering, hanging and buffering. It looks like on a permanent slow internet connection but i'm on a 100mbit line.
It only happens with live stream.
Restart isn't working with the actual ZIB2 stream but without problems with ORF3 "Themenmontag".

**Comment by Azulath** [comment]
> Just tested running the ZIB2 live stream. I keeps stuttering, hanging and buffering. It looks like on a permanent slow internet connection but i'm on a 100mbit line. It only happens with live stream. Restart isn't working with the actual ZIB2 stream but without problems with ORF3 "Themenmontag".

I'm having the same issue on Matrix.

**Comment by s0faking** [comment]
please provide some debug logs of the issue (enable compenent specific logging for curl, ffmpeg and video component as well)

**Comment by UserX404** [comment]
> please provide some debug logs of the issue (enable compenent specific logging for curl, ffmpeg and video component as well)

Sent you a mail with logs to the address in your Git profile.

**Comment by mhochsteger** [comment]
Hi,

I also experience the stuttering/hanging (CoreELEC on Odroid C2 device) on some streams (Zib2 for instance). At the same time, I also see unusually high CPU usage. Selecting the lowest quality stream seems to improve a bit (still hanging every few seconds).
Maybe the issue is due to missing GPU acceleration in certain streams?
A log file is attached, the following lines appear during the stream:
```2022-02-02 22:21:50.556 T:3531600768  NOTICE: CVideoPlayerAudio::Process - stream stalled pts:17584685.653 clock:17584685.660
2022-02-02 22:21:52.059 T:3555021696 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
2022-02-02 22:21:54.115 T:3531600768  NOTICE: CVideoPlayerAudio::Process - stream stalled pts:17584687.573 clock:17584687.574
2022-02-02 22:21:57.477 T:3531600768  NOTICE: CVideoPlayerAudio::Process - stream stalled pts:17584689.493 clock:17584689.499
2022-02-02 22:21:59.019 T:3555021696 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
2022-02-02 22:22:00.976 T:3531600768  NOTICE: CVideoPlayerAudio::Process - stream stalled pts:17584691.413 clock:17584691.422
```
[kodi.log](https://github.com/s0faking/plugin.video.orftvthek/files/7990181/kodi.log)

I can also do tests on a branch, if needed.

Best,
Matthias

**Comment by s0faking** [comment]
the timout messages seem to indicate that the player doesn't get the new stream data in time (UserX404s logs had pretty much the same messages). i can't really reproduce the issue on my nvidia shield and laptop though. do you have this problem with every livestream or only the popular ones? for now it looks like the tvthek servers can't handle the load to me.

**Comment by UserX404** [comment]
Zib1 and zib2 were affected since this issue was reported.
Other streams are working (live/restart) without issues.
But the affected shows have no issues when they are available in "recent shows".
I also have no clue if only the (or all) news shows are affected. (personal time schedule)

**Comment by Gghuzr** [comment]
> Just tested running the ZIB2 live stream. I keeps stuttering, hanging and buffering. It looks like on a permanent slow internet connection but i'm on a 100mbit line.
> It only happens with live stream.
> Restart isn't working with the actual ZIB2 stream but without problems with ORF3 "Themenmontag".

Stuttering can also affected by the Widewine Version. On several devices downgrade of widewine via inputhelper solved this problems

**Comment by s0faking** [comment]
also a possibility, @UserX404 could you try downgrading/upgrading your widewine version? you can change the versions with the program addon from this repo: https://k.slyguy.xyz

**Comment by UserX404** [comment]
@s0faking 
In the program addon list of this repo are only 'GPIO Monitor', 'IPTV Merge', and 'NOOBS Companion'.

**Comment by s0faking** [comment]
Checkout this Guide: https://www.matthuisman.nz/2021/05/widevine-arm-broken.html

**Comment by Azulath** [comment]
I have difficulties providing logs since my LibreELEC device is at me secondary living place. That being said, according to the discussions going on here this does seem to be a Widevine related issue, doesn't it?

**Comment by UserX404** [comment]
@s0faking 
Sent you updated logs with widevine  4.10.2252.0

**Comment by UserX404** [comment]
Can report the problematic ZIB2 live stream is working again but restart is not possible.

**Comment by mhochsteger** [comment]
Same here, downgrading widevine solved the issue. Thanks for the help!

**Comment by Azulath** [comment]
@mhochsteger Which version of widevine are you using?

**Comment by mhochsteger** [comment]
@Azulath I am now running 4.10.2252.0 (13816.82.0)

**Comment by UserX404** [comment]
@mhochsteger 
What system are you running on and is Restart working for you with all streams?

**Comment by Walker7401** [comment]
Hi, I'm running Kodi 19.3 on QNAP NAS in x86_64 linux. Inputstream Helper is 0.5.8+matrix.1, Inputstream Adaptive is 19.0.0, WideVine is 4.10.2391.0, ORF TV Thek is 0.12.4+matrix.1
As of now 06-FEB-2022 13:00 ORF1 (olympia), ORF2 (ZIB) licestreams do work, may be paused, restarted and work again like a charm.
After reading all your comments and after a lot of fiddeling around I uninstalled every video add-on on kodi and as well deleted video-related addons in the filesystem of kodi. Then I re-installed TVTHEK and of course it's now missing dependancies, and hooray, it works (even with a newer version of widevine than @mhochsteger is reporting)

**Comment by Azulath** [comment]
> please provide some debug logs of the issue (enable compenent specific logging for curl, ffmpeg and video component as well)

You can find my logs here:
http://ix.io/3OYC

@mhochsteger I have downgraded to 4.10.2252.0 (13816.82.0), but it hasn't resolved the issue. I have also unistalled ORF, Netflix and InputstreamHelper (cannot uninstall Inputstream Adaptive) and re-installed them but this also did not resolve the issue.

**Comment by Gghuzr** [comment]
@Walker7401 

The widewine issue is mostly impacted on ARM plattforms like Raspi or E2 receiver and not x64

**Comment by Azulath** [comment]
ORF 0.12.4 and Widevine does seem to work now after re-installing and downgrading with SlyGuy's addon.

**Comment by gsantner** [comment]
Oh so the "new drm" release isn't available on repos yet?

**Comment by gsantner** [comment]
The 0.12.4 seems to work good enough on quick test. As anyway the current release doesn't work at all, I'd suggest to move the 12.4 pre-release to normal release so it gets available in repos...the current available version in repos is worthless in current state^^

**Comment by gsantner** [comment]
The 0.12.4 seems to work good enough on quick test. As anyway the current release doesn't work at all, I'd suggest to move the 12.4 pre-release to normal release so it gets available in repos...the repo version is worthless in current state^^

sorry for previous comment, I thought the repo version is the latest release.

**Comment by UserX404** [comment]
Live video is working since the Widevine rollback but does nobody have issues with the resart feature?
As mentioned before Zib1/2 streams doesn't work for me with resart and i'm wondering this happens only to me.

**Comment by s0faking** [comment]
i just pushed the update to the offical repo. for now use the zip files from the release page

**Comment by s0faking** [comment]
> Live video is working since the Widevine rollback but does nobody have issues with the resart feature? As mentioned before Zib1/2 streams doesn't work for me with resart and i'm wondering this happens only to me.

i tried to reproduce this. also with zib1/2 but i wasn't able to get the same behaviour. restart streams play flawless on my test systems. according to the log the request to the restart is denied, the only way i can get the same error is when i wait until the restart is not available anymore (thats always after the show has ended afaik) and use the restart button. thats normal behaviour though
