### ISSUE TITLE
ORF 1/2 livestream / license acquire broken again

### ISSUE THREAD

**Issue by HiassofT** [s0faking/plugin.video.orftvthek#122]
I initially noticed that on LibreELEC 9.2 (Kodi Leia 18.7) running on an RPi4 with orftvthek plugin 0.12.4 and widevine 4.10.2252 and now tested on current LibreELEC 10 branch (Kodi Matrix 19.4, up-to-date with Kodi Matrix branch), orftvthek plugin 0.12.5 and widevine 4.10.2449 with the same result.

Earlier this week livestream worked fine but when I tested again yesterday I got a 502 from the license request
```
2022-08-06 19:24:16.172 T:1085    ERROR <general>: CCurlFile::Open failed with code 502 for https://drm.ors.at/acquire-license/widevine?BrandGuid=13f2e056-53fe-4469-ba6d-999970dbe549&userToken=0B2t9%2BAyWdyn4oA9hPJXdFmWEIg3UKThOe1EaVJjtyZqueXwupf7V7enDZGg95%2FKl6NinC3Z7rbIZOBSHJcaiAHU%2FXhj1mOG%2FVHBnZiZi9Q8I6mnuexJMw%2F%2BY4HApC4J1U66MvF6q7KdlAloJAxiTiaYtvaiYXYCtWXd1gqlxpmIY6Hkf8FGq23w2r7CqAsRyzhLAqOt92KxIuRY1W7suH7QePC1kRzVaQ9jGT%2Fbk6RlpJ8v9%2BilOuPZq1Cb1SnN:
                                                   <html>
                                                   
2022-08-06 19:24:16.172 T:1085    ERROR <general>: AddOnLog: inputstream.adaptive: License server returned failure
```
Full debug log with curl component logging enabled is here: http://ix.io/46Qu

From a quick glance at the firefox network tab the ORF TVthek website uses the same license URL but switched content type to application/octet-stream and sends a binary payload - so probably something changed recently

**Comment by s0faking** [comment]
thank you. i'll look into it. probably something similar to the fix in #118

**Comment by jaylinski** [comment]
Changing `Content-Type=text/xml` to `Content-Type=application/octet-stream` seems to fix the issue.

**Comment by s0faking** [comment]
https://github.com/s0faking/plugin.video.orftvthek/releases/tag/0.12.5

**Comment by s0faking** [comment]
should be fixed with this version

**Comment by 1Luc1** [comment]
just tested it with version 0.12.5. works like a charm.

**Comment by HiassofT** [comment]
Thanks a lot, latest release works fine here, too!

**Comment by haubi** [comment]
Live streams work again, thanks!
But their Restart still is broken: Same issue, same fix does help as well - again in file resources/lib/Addon.py, but on line 206.

**Comment by Gghuzr** [comment]
You are really the King - superfast Fix and Event live Streams are also inclusive w/o workaround ;-)

**Comment by s0faking** [comment]
sorry my bad. restart should be fixed with 0.12.6

**Comment by prettyv** [comment]
Thanks a lot, could you make a PR to update the version in the official repositories as well please? :)

**Comment by s0faking** [comment]
already did that but the pr hasn't been approved yet

https://github.com/xbmc/repo-plugins/pull/4086

**Comment by prettyv** [comment]
Oh, don't know how I missed that, sorry for the noise. Let's hope this will be approved soon, using the release version from here is also fine in the meantime.
