### ISSUE TITLE
Special Livestreams do not work

### ISSUE THREAD

**Issue by Gghuzr** [s0faking/plugin.video.orftvthek#125]
I do not have success to Stream the Special Livestream via this Kodi -Addon (after 20 sec „replay is not possible“)

With the same Setup it works via web Browser and the official ORF App

On the Kodi Version 12.6 it works only on ORF1, ORF2 and ORF Sport+(with buffer issues)livestreams and Mediathek content. ORF3 has no reaction by Click on. 

Latest Widevine in use (also tried over the Old Service api + Livestream w/o success)

So a lot Problems for watching over Kodi

**Comment by s0faking** [comment]
can you supply some debug logs? what kodi version /pi distro are you running? does this issue only apply to special livestreams?

the buffer issues are related to the widevine libarary on raspberry pis. unfortunately theres nothing i can do about this from the addon scope. trying to up/downgrading the widevine version until the issue disappears seems to be the only solution for this so far.

**Comment by Gghuzr** [comment]
Thanks for your support in advance - attached the debug log




[kodi.log](https://github.com/s0faking/plugin.video.orftvthek/files/9893709/kodi.log)

**Comment by Gghuzr** [comment]
Thx for your Support in advance
[kodi.log](https://github.com/s0faking/plugin.video.orftvthek/files/9893721/kodi.log)

**Comment by s0faking** [comment]
thanks. can you export another debug log with component specific logging for "libcurl" & "video component" enabled. just tried it on a few devices with the same settings and livestream special you used and it worked everywhere. 

from your logs i can just see that ffmpeg stops loading the stream with a tls error. in the log it says you are using "Kodi (19.4 (19.4.0) Git:20221023-24502c2821c-dirty)"  is this part of any distribution you are using or did you build it yourself?

**Comment by Gghuzr** [comment]
Here the debug log for the non working ORF3HD Livestream, others Logs and infos will follow
[kodi.log](https://github.com/s0faking/plugin.video.orftvthek/files/9893760/kodi.log)

**Comment by Gghuzr** [comment]
Ok, here the log with extra libcurl" & "video component

I use Kodi 19.4 on E2 Receiver(not Own built) for the Test (with clean Image) Same issue also on Raspberry 3b+ with libreelec 10.0.3 and Xbian 19.4 as OS
[kodi.log](https://github.com/s0faking/plugin.video.orftvthek/files/9893780/kodi.log)

**Comment by s0faking** [comment]
please try it with https://github.com/s0faking/plugin.video.orftvthek/releases/tag/0.12.7

**Comment by Gghuzr** [comment]
Feedback to ORF3HD
Livestream link starts now but Playback fails at the end

[kodi.log](https://github.com/s0faking/plugin.video.orftvthek/files/9945623/kodi.log)

Feedback to Special live Streams will follow in the afternoon (Judo Special live Stream)

**Comment by Gghuzr** [comment]
Unfortunately the Special live Stream is still not working. Here the debug log

[kodi.log](https://github.com/s0faking/plugin.video.orftvthek/files/9945906/kodi.log)

**Comment by s0faking** [comment]
the problem with the special livestream should be fixed with the latest commit on master. there was an issue with the url get parameter removal. 

your issue with the orf3 stream on the other hand seems to be a core issue. all scraped videourls look good (i compared it to a working request on a pi & linux desktop) but the player stops on line 1608 with

`ffmpeg[0x37b9b90X]: [tls] error:00000000:lib(0):func(0):reason(0)`

this looks like there might be something wrong with openssl, not really sure tough. it might help if you try the same things on your pi and send me the debug logs.

**Comment by Gghuzr** [comment]
Mhh still struggled with the Special live Stream...

using you matrix Update 16min. Ago
[kodi.log](https://github.com/s0faking/plugin.video.orftvthek/files/9946065/kodi.log)

**Comment by s0faking** [comment]
yes the log looks like the one from orf3 now. before you got a 403 on the videourl because the last character was cut from the url by my last fix. now special livestreams also return 

`error:00000000:lib(0):func(0):reason(0)`

can you try the same thing on your rasperry pi and post the logs?

**Comment by Gghuzr** [comment]
Same issue with the Raspberry 

Strange if I copy the manifest.m3u8 Link from ORF3HD then it opened up on other browser device (eg.Safari Browser on iPad). So it seems a videocodec related topic

**Comment by Gghuzr** [comment]
Finally the live Event Streams are working now. Big Thx to s0faking!

ORF3 HD still does not work, but there other options in use for watching the channel
