### ISSUE TITLE
IPTV AutoExec Service

### ISSUE THREAD

**Issue by SilPan** [s0faking/plugin.video.orftvthek#128]
Please apologize the stupid question.
I am unable to get Kodi to be an IPTV.

I want it to play ORF2 as soon as Kodi starts.

I create an AutoExec Service as described here https://kodi.wiki/view/Autoexec_Service.

`autoexec.py` contains:
```
import xbmc
xbmc.executebuiltin( "ActivateWindow(Videos,plugin://plugin.video.orftvthek/?channel=orf2ooe&mode=pvr)" )
```

When I start Kodi the ORF plugin is started, but I get displayed an empty menu.
![Imagepipe_396](https://user-images.githubusercontent.com/36964752/209819021-f49c7ad7-2f92-4679-8141-cad014abd252.jpg)

Is this the indented way to do it?

**Comment by s0faking** [comment]
you'll have to use "PlayMedia". ActivateWindow will only open a listing not the player. Checkout https://kodi.wiki/view/List_of_built-in_functions for more infos on the built-in functions

```
xbmc.executebuiltin( "PlayMedia('plugin://plugin.video.orftvthek/?channel=orf2ooe&mode=pvr') ")
```

**Comment by SilPan** [comment]
Ah yes, thank you!
Amd thank you so much for maintaining this addon <3
