### ISSUE TITLE
Videos start to stutter if paused for too long

### ISSUE THREAD

**Issue by Esokrates** [s0faking/plugin.video.orftvthek#131]
When I pause videos for too long and try to continue, the audio kind of continues, but in a very choppy manner and the video appears frozen or very choppy.
This is not the case for live streams.

Ways to reproduce:

1. Play ZIB 1 of the days before
2. Press pause and wait for a few minutes, e.g. 5 minutes
3. Try to resume by pressing play
4. Observe, that the video does play is it did before.

Exiting and restarting the video from the last position resolves the issue, but this is annoying.

**Comment by s0faking** [comment]
sorry i can't reproduce this issue. tried it with the playlist items and the full stream. can you post a debug log with the issue occuring? what os/system are you using?

**Comment by Esokrates** [comment]
@s0faking Sorry for the late reply, I'll try to get a debug log next time. Using Kodi on Android TV, issue is still reproducible.

**Comment by s0faking** [comment]
closed due to inactivity. please reopen if this is still an issue
