### ISSUE TITLE
Only one option availble in kodi when multiple streams are offered

### ISSUE THREAD

**Issue by mimre25** [s0faking/plugin.video.orftvthek#133]
Hi,

I noticed that when there are multiple streams offered (eg for the ZIB), only one of them is available in kodi.

I'd be happy to contribute a fix if this is wanted/desired :slightly_smiling_face:

**Comment by s0faking** [comment]
Hi Martin,

Thanks for the issue. I've added a commit to fix the issue. Have to test this with the bundesland and special livestreams before I push the version to the repo. I only was able to test the scraper with Wayback Timemachine for now but the livestream detail endpoints have to be tested on the website to make sure everything works. Contributions are always welcome btw :)

**Comment by mimre25** [comment]
I've checked out the latest  master, but unfortunately today I couldn't see any of the streams that were previously missing (ZIB 1 in this case). 

Are there any debug logs that I can access? has it worked in your tests?

**Comment by s0faking** [comment]
yep, haven't seen the problem since the last commit. did you rename the folder when downloading the zip generated by github before installing the addon? the folder name has a "-master" (plugin.video.orftvthek-master) on the end which might cause kodi to run the old version. in my tests i always saw both streams the default one and the one with audio description.

**Comment by mimre25** [comment]
I just pulled the git repo into `~/.kodi/addons/` and replaced the old folder.

Just tested it again: 
ZIB on ORF2 has 2 streams now: `ZIB` and `ZIB (OeGS)`. 

With the latest master it doesn't show either, with `0.12.9` it shows only `ZIB (OeGS)`

**Comment by s0faking** [comment]
ok, i will check this again today. only tested it on zib2 yesterday which showed both streams the ÖGS and the regular stream. i saw that the bundesland streams were broken with the last commit so that should be fixed again on the latest master commit.

**Comment by s0faking** [comment]
![screenshot00000](https://github.com/s0faking/plugin.video.orftvthek/assets/3915825/cea7416c-8d87-40d9-9cd8-d2ac2f2aa5b6)

seems to work as expected

**Comment by mimre25** [comment]
FYI: I have now switched from OSMC to Raspberry Pi OS and have installed the latest kodi on there.
Now everything works just as you describe it. :+1:
