### ISSUE TITLE
Komplettausfall

### ISSUE THREAD

**Issue by DIY-Blub** [s0faking/plugin.video.orftvthek#138]
Hallo,

zuerst einmal Danke für die tolle Arbeit die du / ihr mit euren Plugins hier vollbringt :+1: 

Seit gestern funktioniert das Plugin leider gar nicht mehr. Das Hauptmenü vom Plugin wird angezeigt, aber alle Untermenüs sind leer. Bereits favorisierte Einträge von Sendungen erzeugen folgenden Error:

![Fehlermeldung](https://github.com/s0faking/plugin.video.orftvthek/assets/60984430/b449989d-adbd-411f-8091-e102803d6b85)
(zusammen gestückelte Fotos, sorry :D )

Scheinbar gibt es eine Sicherheitswarnung seitens Python.

Schöne Grüße!

**Comment by killerbees19** [comment]
Für diese Lösung musst Du (afaik) Kodi 19 oder neuer verwenden. Ansonsten ignoriere, was hier steht!

Aktiviere in den Einstellungen des Addons die **Service-API**, dann sollte es wieder klappen. Und falls noch nicht getan, installiere vorerst den `master` Branch von GitHub: [ZIP-Datei herunterladen](https://github.com/s0faking/plugin.video.orftvthek/archive/refs/heads/master.zip) (_Wiki: [How to install from a ZIP file](https://kodi.wiki/view/Add-on_manager#How_to_install_from_a_ZIP_file)_)

(Nur dort ist z.B. #137 bereits behoben.)

**Comment by s0faking** [comment]
du kannst folgenden release verwenden (hier wird die ServiceAPI geforced, dh. deine alten bookmarks werden damit nicht wieder funktioniern)
