### ISSUE TITLE
ORF TVthek -- "Aktuelle Sendungen":  Script-fehler 

### ISSUE THREAD

**Issue by typestar** [s0faking/plugin.video.orftvthek#14]
Hallo Lieber s0faking,

in der aktuellen Version kann ich die "Sendungen" - "aktuelle Sendung" -- und damit alle regionalen TV-Archive (Bundesländer-Ausgaben) nicht öffnen:
"Scriptfehler" ...

DANKE, wenn du dich dieser wieder annimmst, wäre nämlich schon wichtig!
liebe Grüße:  typestar

**Comment by s0faking** [comment]
hi typestar,

werds mir morgen mal ansehen. du kannst aber in der Zwischenzeit die serviceAPI benutzen. Der fehler tritt nur beim htmlscraper auf, vermutlich hat sich da wieder was an der website geändert.


LG s0faking

**Comment by s0faking** [comment]
der fehler ist behoben. update ist unterwegs ins official repo.
