### ISSUE TITLE
Kodi 21

### ISSUE THREAD

**Issue by alexred1611** [s0faking/plugin.video.orftvthek#144]
Servus,

I thought I’m quite techie but I seem to struggle the add on. 
I’ve tried the Kodi > install from zip file route and a few variations but can’t seem to add it as an add on. Any idea what I’m doing wrong here?

Thank you for what looks like a great add on.

alex

**Comment by s0faking** [comment]
Hey Alex 

You can just Install from the official KODi addon repo. No need for a ZIP install

**Comment by alexred1611** [comment]
Ah brilliant, thank you.

Alex
