### ISSUE TITLE
Geo block active

### ISSUE THREAD

**Issue by alexred1611** [s0faking/plugin.video.orftvthek#145]
Servus,

Add-on working but seems despite Austrian IP (two different VPNs) I always only see Geo Block active. 

Do you have any suggestion for that?

danke,
Alex

**Comment by s0faking** [comment]
Does ORFOn on the Browser or the App using the same VPN? It's possible that the geocode check detects the vpn and blocks the access

**Comment by s0faking** [comment]
closed due to inactivity. please reopen if this is still an issue
