### ISSUE TITLE
Livestream

### ISSUE THREAD

**Issue by mariomurrent-softwaresolutions** [s0faking/plugin.video.orftvthek#19]
The video is not working in the livestream if the audio output is set to hdmi & analog. The sound works perfect, but the video stays black.

**Comment by s0faking** [comment]
Please post your testing enviorment (Hardware,OS,Service API or HTML Scraper). A debug log file would be useful aswell to get to the bottom of the issue. 

At the moment it sounds like a Kodi related issue

**Comment by mariomurrent-softwaresolutions** [comment]
I'm using a raspberry pi 2 with raspbian OS. I will try to get a log file. Sometimes the live stream for ORFII is working, but when I switch to ORF Sport+ the screen stays black and no video is visible
