### ISSUE TITLE
No ORF1HD, just SD

### ISSUE THREAD

**Issue by Me4Linux** [s0faking/plugin.video.orftvthek#25]
Hi, s0faking,

since summer (since the European Championship exactly) the plugin delivers ORF1 Livestreams just in SD (960x540) quality while ORF2, ORFIII and ORF Sport are streamed in HD (1280x720). Also archived ORF1 streams ("ORF Tipps", "Sendung verpasst?") are in HD. 

Regards,
Me4Linux

PS: this happens on all devices (Raspberry Pi with OpenELEC/LibreELEC, Kodi on Win7/Linux). All the software and systems are up to date.

**Comment by s0faking** [comment]
Hi,

Looks like the HD Playlist for the Livestream is delivering the wrong videofile. i have to take a look at the website when theres a available livestream, to find out what the problem is. i will get back to you when i did

cheers,
s0fa

**Comment by s0faking** [comment]
Looks like the HD Stream Endpoint just serves a 540p Video.

http://apasfiisl.apa.at/f4m/orf1_q8c/orf.sdp/manifest.f4m

The same goes for the website. I can't see much of a difference between quality setting "Hoch" and "Sehr Hoch"

**Comment by Me4Linux** [comment]
Hi, thank's for the quick reply to my request. During the EM this summer the ORF experienced some serious bandwidth problems (at least that's what I had during the soccer match streams) so they decided to put the SD stream over the HD stream link. Probably they simply forgot to change it back?

**Comment by s0faking** [comment]
i'm pretty sure they left it like that on purpose to save some money on the server infrastucture
