### ISSUE TITLE
Willkommen Österreich

### ISSUE THREAD

**Issue by polojoe** [s0faking/plugin.video.orftvthek#30]
Can't watch latest show of Willkommen Österreich with this addon. Playback doesn't start. Playback on website is OK.

**Comment by s0faking** [comment]
which version are you using?

**Comment by polojoe** [comment]
Version 0.5.5

**Comment by s0faking** [comment]
Try the latest version (0.5.7). just pushed a few updates which seem to fix the issue.

**Comment by polojoe** [comment]
All gold now. Thanks mich!

**Comment by polojoe** [comment]
All good now, thanks much. :-)
