### ISSUE TITLE
Shows with chapters dont play "play all". Only single chapter selections possible.

### ISSUE THREAD

**Issue by xyladecor** [s0faking/plugin.video.orftvthek#32]
First THANK YOU VERY MUCH for this great plugin and the quick fixes!

All shows i tested are running now (with 0.5.7).

The only issue is that that shows with chapters only works if i select chapter(s), the PLAY ALL function still dont work with the message ""Error! Try another item or exit and submit /tmp/e.log. More info on "Tips" on info screen. But this e.log file on /tmp/" is always empty.

This means you have to select each chapter of a show manually, cause after playing the chapter the video stops, unfortunately it dont play further to the next chapter. You have to go back to the chapter selection of the show and pick up the next chapter. Thats a bit awkward with shows with many chapters (a. s. PRESSESTUNDE).

**Comment by s0faking** [comment]
when you open a show, kodi should asks you if you want to start the video right away or see the overview listing(Yes/No Dialog). if you choose to play the videos right away, all the videos are added to a playlist. once the video has started you can navigate with next/prev chapter. 

i will take a look at the faulty "Play All" listitem asap

cheers,
s0fa

**Comment by s0faking** [comment]
nevermind. i see what you mean now. i'll come back to you when i know whats causing this

**Comment by s0faking** [comment]
the error should be fixed with 0.5.8

**Comment by xyladecor** [comment]
Thank you very much for your great work and this support. (Falls okay gehts auch in deutsch). 

Your 2 plugins orf und puls4 are a dream!

ciao
Mickey

  ----- Original Message -----
