### ISSUE TITLE
Daily shows only offers the last edition

### ISSUE THREAD

**Issue by xyladecor** [s0faking/plugin.video.orftvthek#33]
Daily shows like ZIB, Landesstudios (Wien heute, Burgenland heute, and others) only lists the newest edition to select. Usually each daily edtiion is available 7 days, so at the moment ZIB2 shows only the edition from friday 14.10.2016. ZIB 2 shows from 13.10., 12.10. 11.10. 10.10. are not listed.

**Comment by s0faking** [comment]
already opened a ticket for that. #29
