### ISSUE TITLE
problem with playing "chaptered" shows still exists

### ISSUE THREAD

**Issue by xyladecor** [s0faking/plugin.video.orftvthek#35]
I now tried 0.5.9 with kodi direct 3.1 (on an enigma2 STB box), it works fine. The only problem still exists is the point that i have to select each single chapter to play, and not to play the whole show in one. Not sure, maybe it is also a problem with this kodi version for set top boxes, but til a few weeks it was no problem to play chaptered shows in whole.

**Comment by Rechi** [comment]
Are you using the `ServiceAPI`? Because I haven't implemented a play all yet.

**Comment by xyladecor** [comment]
I think not. This/my "Kodi Direct" version seems a "lean version" of Kodi, for enigma Set-Top-Boxes, cause there are not any settings available, the only settings options are these -> https://www.dropbox.com/s/ouk7xm2dftr13r7/007.png?dl=0

I am afraid this "lean" Kodi Direct version is the reason for this problem.

**Comment by s0faking** [comment]
if you open the context menu while using the tvthek addon there should be an item "addon settings". then you should be able to enable/disable the serviceAPI option. 

do you have any possibility to get some debug log files from the error mentioned above?

**Comment by xyladecor** [comment]
When i select SETUP in the ORF TVthek plugin i have this options -> https://www.dropbox.com/s/hhxns76rr7wazp1/007.png?dl=0

I see nothing about a serviceAPI, i am afraid this KODI DIRECT dont contain it, for any reason.

I will try to find out how i can get a debug log on this, cause without such a log file (which is always emtpy at the moment) it is the seek of the needle in the sack.

But your plugin´s (puls4 und orf) are great, i love them! Thanks for the work!

**Comment by s0faking** [comment]
thx @xyladecor. well looks like kodi direct doesnt handle the addon structure quite well. maybe something went wrong when u updated the addon. you could try remove the addon completely and reinstall. those are the settings that should be visible:
https://github.com/s0faking/plugin.video.orftvthek/blob/master/resources/settings.xml

cheers,
s0fa

**Comment by xyladecor** [comment]
My fault. on setup there is a line with "serviceAPI", i have changed the font size smaller, now there are mor otpions on the setup menu. So there was "false" on serviceAPI, now i have switched to "true", but it dont help, each chaptered show stopps after a chapter and i have to select the next chapter to play manually. https://www.dropbox.com/s/gk83ndv319nrs0r/007.png?dl=0

Settings.xml on my box looks like so:

<settings>
    <setting id="forceView" type="bool" label="30021" default="true" />
    <setting id="autoPlayPrompt" type="bool" label="30028" default="true" />
    <setting id="useSubtitles" type="bool" label="30029" default="false" />
    <setting id="useServiceAPI" type="bool" label="30026" default="true" />
    <setting id="enableBlacklist" type="bool" label="30043" default="true" />
    <setting id="videoQuality" type="enum"  label="30022" lvalues="30023|30024|30025|30044" default="30044"/>
</settings>

Its serious, but to play chaptered shows worked on earlier versions without any problems, there was only a short freezer betwwen the chapters.

**Comment by xyladecor** [comment]
I could fix kodi that i now get a log output. Maybe this can give you an overview why it dont play the whole show, the log says. (i used the show Bürgeranwalt")

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Here in default-py sys.argv = ['/usr/lib/enigma2/python/Plugins/Extensions/KodiDirect/plugins/plugin.video.orftvthek-master/default.py', '5', '?plugin://plugin.video.orftvthek-master/?link=1339&mode=openProgram']
Here in default-py sys.argv B= ['plugin://plugin.video.orftvthek-master/', '5', '?link=1339&mode=openProgram']
CommonFunctions-2.5.1
xbmcplugin addDirectoryItem plug in url
xbmcplugin addDirectoryItem 1
xbmcplugin addDirectoryItem data B = &name=[-Play-all-]&url= &thumbnailImage=DefaultFolder.png&iconlImage=http://api-tvthek.orf.at/uploads/media/segments/0001/24/thumb_23248_segments_highlight_teaser.jpeg&url=/usr/lib/enigma2/python/Plugins/Extensions/KodiDirect/plugins/plugin.video.orftvthek-master/default.py?plugin://plugin.video.orftvthek-master/?modeExQplaylist

xbmcplugin addDirectoryItem 1
xbmcplugin addDirectoryItem data B = &name=Signation-|-BegrÃ¼ÃŸung&url= &thumbnailImage=DefaultFolder.png&iconlImage=http://api-tvthek.orf.at/uploads/media/segments/0001/24/thumb_23248_segments_highlight_teaser.jpeg&url=http://apasfpd.apa.at/cms-worldwide/online/b501afaae8bded1c42c2be7a7c95af2e/1477605605/2016-10-22_1730_tl_02_BUERGERANWALT_Signation---Beg__13891818__o__6863279358__s13897677_7__ORF2HD_17295303P_17303122P_Q6A.mp4

xmbc data B= &url=http://apasfpd.apa.at/cms-worldwide/online/b501afaae8bded1c42c2be7a7c95af2e/1477605605/2016-10-22_1730_tl_02_BUERGERANWALT_Signation---Beg__13891818__o__6863279358__s13897677_7__ORF2HD_17295303P_17303122P_Q6A.mp4&name=

xbmcplugin addDirectoryItem 1
xbmcplugin addDirectoryItem data B = &name=Taxis-akzeptieren-oft-keine-Blindenhunde&url= &thumbnailImage=DefaultFolder.png&iconlImage=http://api-tvthek.orf.at/uploads/media/segments/0001/24/thumb_23249_segments_highlight_teaser.jpeg&url=http://apasfpd.apa.at/cms-worldwide/online/395e63f5ea55425d29c063fd1818df25/1477605605/2016-10-22_1730_tl_02_BUERGERANWALT_Taxis-akzeptier__13891818__o__1306364171__s13897678_8__ORF2HD_17303122P_17445705P_Q6A.mp4

xmbc data B= &url=http://apasfpd.apa.at/cms-worldwide/online/395e63f5ea55425d29c063fd1818df25/1477605605/2016-10-22_1730_tl_02_BUERGERANWALT_Taxis-akzeptier__13891818__o__1306364171__s13897678_8__ORF2HD_17303122P_17445705P_Q6A.mp4&name=

xbmcplugin addDirectoryItem 1
xbmcplugin addDirectoryItem data B = &name=Auswirkungen-der-Verhandlungen-Ã¼ber-das-iranische-Atomprogramm&url= &thumbnailImage=DefaultFolder.png&iconlImage=http://api-tvthek.orf.at/uploads/media/segments/0001/24/thumb_23250_segments_highlight_teaser.jpeg&url=http://apasfpd.apa.at/cms-worldwide/online/6c14be8892282bbc39c4d89dcc9645b3/1477605605/2016-10-22_1730_tl_02_BUERGERANWALT_Auswirkungen-de__13891818__o__1081396158__s13897679_9__ORF2HD_17445705P_17530302P_Q6A.mp4

xmbc data B= &url=http://apasfpd.apa.at/cms-worldwide/online/6c14be8892282bbc39c4d89dcc9645b3/1477605605/2016-10-22_1730_tl_02_BUERGERANWALT_Auswirkungen-de__13891818__o__1081396158__s13897679_9__ORF2HD_17445705P_17530302P_Q6A.mp4&name=

xbmcplugin addDirectoryItem 1
xbmcplugin addDirectoryItem data B = &name=Bau-der-Nordautobahn:-ASFINAG-macht-sich-unbeliebt&url= &thumbnailImage=DefaultFolder.png&iconlImage=http://api-tvthek.orf.at/uploads/media/segments/0001/24/thumb_23252_segments_highlight_teaser.jpeg&url=http://apasfpd.apa.at/cms-worldwide/online/bdaf7f5229f23d1c68b288232fd6ee6d/1477605605/2016-10-22_1730_tl_02_BUERGERANWALT_Bau-der-Nordaut__13891818__o__5087826065__s13897680_0__ORF2HD_17530302P_18125322P_Q6A.mp4

xmbc data B= &url=http://apasfpd.apa.at/cms-worldwide/online/bdaf7f5229f23d1c68b288232fd6ee6d/1477605605/2016-10-22_1730_tl_02_BUERGERANWALT_Bau-der-Nordaut__13891818__o__5087826065__s13897680_0__ORF2HD_17530302P_18125322P_Q6A.mp4&name=
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

**Comment by s0faking** [comment]
hi @xyladecor ,

hm the logfile looks weird. can you try export a debug log with the following addon

http://kodi.wiki/view/Add-on:Kodi_Log_Uploader

cheers,
s0fa

**Comment by xyladecor** [comment]
I think i have posted a wrong log. I tried again to watch "Bürgeranwalt" with "play all", that brings this log; i think this looks much useful as a log:

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Here in default-py sys.argv = ['/usr/lib/enigma2/python/Plugins/Extensions/KodiDirect/plugins/plugin.video.orftvthek-master/default.py', '15', '?plugin://plugin.video.orftvthek-master/?mode=playlist']
Here in default-py sys.argv B= ['plugin://plugin.video.orftvthek-master/', '15', '?mode=playlist']
CommonFunctions-2.5.1
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Plugins/Extensions/KodiDirect/plugins/plugin.video.orftvthek-master/default.py", line 253, in <module>
    startPlaylist(tvthekplayer,playlist)
  File "/usr/lib/enigma2/python/Plugins/Extensions/KodiDirect/plugins/plugin.video.orftvthek-master/default.py", line 157, in startPlaylist
    player.play(playlist)
  File "/usr/lib/enigma2/python/Plugins/Extensions/KodiDirect/scripts/script.module.main/lib/xbmc.py", line 359, in play
    url = url.items[0].getfilename()  
IndexError: list index out of range
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

I will check this Kodi_Log_Uploader too.

**Comment by Rechi** [comment]
@xyladecor please try 0852aa8

**Comment by xyladecor** [comment]
When i edit the line 204-209 of serviceapi.py the plugin dont start and i geht this error log:

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Here in default-py sys.argv = ['/usr/lib/enigma2/python/Plugins/Extensions/KodiDirect/plugins/plugin.video.orftvthek-master/default.py', '1', '']
Here in default-py sys.argv B= ['plugin://plugin.video.orftvthek-master/', '1', '']
CommonFunctions-2.5.1
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Plugins/Extensions/KodiDirect/plugins/plugin.video.orftvthek-master/default.py", line 27, in <module>
    from resources.lib.serviceapi import *
  File "/usr/lib/enigma2/python/Plugins/Extensions/KodiDirect/plugins/plugin.video.orftvthek-master/resources/lib/serviceapi.py", line 209
    for segment in result.get('_embedded').get('segments'):
    ^
IndentationError: unexpected indent
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

But dont worry, i´m happy how it is. You dont have to make you the work to find the "play all" problem, especially it seems its a problem only on the enigma2 STB´s.

**Comment by Rechi** [comment]
@xyladecor just replace `False` in line 206 with `Ture` or replace the the whole file with https://github.com/s0faking/plugin.video.orftvthek/raw/0852aa8/resources/lib/serviceapi.py

**Comment by xyladecor** [comment]
I have replaced the current service.api with the one in the link above. Still not playing the show (Bürgeranwalt) at once. log says the following:

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Here in default-py sys.argv = ['/usr/lib/enigma2/python/Plugins/Extensions/KodiDirect/plugins/plugin.video.orftvthek-master/default.py', '4', '?plugin://plugin.video.orftvthek-master/?mode=playlist']
Here in default-py sys.argv B= ['plugin://plugin.video.orftvthek-master/', '4', '?mode=playlist']
CommonFunctions-2.5.1
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Plugins/Extensions/KodiDirect/plugins/plugin.video.orftvthek-master/default.py", line 253, in <module>
    startPlaylist(tvthekplayer,playlist)
  File "/usr/lib/enigma2/python/Plugins/Extensions/KodiDirect/plugins/plugin.video.orftvthek-master/default.py", line 157, in startPlaylist
    player.play(playlist)
  File "/usr/lib/enigma2/python/Plugins/Extensions/KodiDirect/scripts/script.module.main/lib/xbmc.py", line 359, in play
    url = url.items[0].getfilename()  
IndexError: list index out of range
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

**Comment by s0faking** [comment]
please reopen if this is still an issue
