### ISSUE TITLE
KodiDirect 3.1 Issue : Not opening .ts ending urls

### ISSUE THREAD

**Issue by marinja** [s0faking/plugin.video.orftvthek#39]
The problem is corelated with start of plugin.video.f4mTester /script.video.F4mProxy.
No one item to play / open with: .ts extension? The other is all in order / fine.
Error log:
Here in default-py sys.argv = ['/usr/lib/enigma2/python/Plugins/Extensions/KodiDirect/plugins/plugin.video.Stallion.IPTV.3.2/default.py', '12', '?plugin://plugin.video.Stallion.IPTV.3.2/?url=plugin%3A%2F%2Fplugin.video.f4mTester%2F%3Furl%3Dhttp%253A%252F%252FXXX.XXX.XX.XXX%253A8080%252Flive%252F5454%252F5454%252F942.ts%26amp%3Bstreamtype%3DTSDOWNLOADER%26name%3DBEIN%25201%2520HD&mode=12']
Here in default-py sys.argv B= ['plugin://plugin.video.Stallion.IPTV.3.2/', '12', '?url=plugin%3A%2F%2Fplugin.video.f4mTester%2F%3Furl%3Dhttp%253A%252F%252FXXX.XXX.XX.XXX%253A8080%252Flive%252F5454%252F5454%252F942.ts%26amp%3Bstreamtype%3DTSDOWNLOADER%26name%3DBEIN%25201%2520HD&mode=12']
CommonFunctions-2.5.1
XXX.XXX.XX.XXX is written by my self for purpose!
Ahy help would be appreciated and welcome.
marinja

**Comment by s0faking** [comment]
is this issue related to #35 ? i dont't have any hardware running kodi direct so it's quite hard to debug/fix this issue. looks like a kodi direct problem for me tough

**Comment by s0faking** [comment]
please reopen if this is still an issue
