### ISSUE TITLE
NO thumbs icons inside with Kodi 14.0 helix / unwinds

### ISSUE THREAD

**Issue by typestar** [s0faking/plugin.video.orftvthek#4]
Dear s0faking,

thankyou for the ORF Plugin -
BUT:  it does not show thumbs of the single themes/ casts inside at the start - so this really looks "ugly".
Only the icon, that starts the plugin can be seen...

Danke für dein ORF-Plugin!
Leider sieht man beim Start des Plugins am Anfang keinerlei Vorschaubilder in der Auswahl der Themenbereiche, wie es z.B. in der Originalen ORF-TV-thek der Fall ist.

Ich arbeite hier auf einem amazon Fire-TV auf dem Kodi 14.0 helix unwinds läuft...
Danke, wenn du dich der Sache annimmst...

Viele Grüße und vielleicht kriegst dus hin...

typestar

(edited to say it clearer)

**Comment by s0faking** [comment]
Hi,

i will look into it. thx for the feedback

LG
s0faking

Am 13.01.2015 um 11:07 schrieb typestar:
>
> Dear s0faking,
>
> thankyou for the ORF Plugin -
> BUT: it does not show thumbs of the single themes/ casts inside... - 
> so this really looks "ugly".
> Only the icon, that starts the plugin can be seen...
>
> Danke für dein ORF-Plugin!
> Leider sieht man innerhalb des Plugins dann keinerlei Vorschaubilder 
> der Sendungen bzw. auch nicht deren logos, wie es z.B. in der 
> Originalen ORF-TV-thek der Fall ist...!
> Ich arbeite hier auf einem amazon Fire-TV auf dem Kodi 14.0 helix 
> unwinds läuft...
> Danke, wenn du dich der Sache annimmst...
>
> Viele Grüße und vielleicht kriegst dus hin...
>
> typestar
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/s0faking/plugin.video.orftvthek/issues/4>.
>

-- 

  -=[============]=-

   .lowfidelity OG
   Daniel Weidacher

[Senior Bootstrapper]

  www.lowfidelity.at
  dw@lowfidelity.at

   +43 1 9417809
  -=[============]=-

**Comment by typestar** [comment]
s0faking,

to make this issue more clear, what I mean:
At the start of the plugin, If you have choosen "symbols" in a skin a the view-method, then the first screnn-view of "Neue Sendungen", "Sendungen", "Aktuell"  etc. -- there are no icons created for this, they are black -- so it looks as something is "wrong" with it... It seems, that you should create some Icons for this case - as png-text Icons or simular...
Thankyou for all your efforts...

Liebe Grüße und danke,

typestar

**Comment by mablae** [comment]
These are just plain http links pointing to the image. Maybe ORF changed their URL structure or sth like that?

**Comment by s0faking** [comment]
yep. i will change those on sunday and commit the new version.

peeze

Am 15.01.2015 um 02:27 schrieb Malte:
>
> These are just plain http links pointing to the image. Maybe ORF 
> changed their URL structure or sth like that?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/s0faking/plugin.video.orftvthek/issues/4#issuecomment-70025703>.
>

-- 

  -=[============]=-

   .lowfidelity OG
   Daniel Weidacher

[Senior Bootstrapper]

  www.lowfidelity.at
  dw@lowfidelity.at

   +43 1 9417809
  -=[============]=-

**Comment by s0faking** [comment]
just fixed the 404 on the default banner image. update should be in the official repo by tomorrow
