### ISSUE TITLE
ImportError: No module named simplejson

### ISSUE THREAD

**Issue by peletiah** [s0faking/plugin.video.orftvthek#49]
> 19:52:11.389 T:1518334960   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named simplejson
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.orftvthek/default.py", line 7, in <module>
                                                from resources.lib.base import *
                                              File "/home/osmc/.kodi/addons/plugin.video.orftvthek/resources/lib/base.py", line 4, in <module>
                                                import simplejson
                                            ImportError: No module named simplejson
                                            -->End of Python script error report<--
19:52:11.417 T:1958265776   ERROR: GetDirectory - Error getting plugin://plugin.video.orftvthek/
19:52:11.418 T:1958265776   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.orftvthek/) failed

After the most recent update a few days ago, the plugin was throwing an error. Solved it by installing the _python-simplejson_-package

I don't know how dependency-management works on osmc/kodi, hence this bugreport.

**Comment by Rechi** [comment]
What version of Kodi are you using?

**Comment by peletiah** [comment]
> 17.1-RC1 Media Center Kodi

**Comment by s0faking** [comment]
try a fresh install of the addon. simplejson should be download by kodi/osmc (script.module.simplejson).
maybe the problem is that you running the RC version. isn't there a stable kodi release built into the current osmc version? i currently  got no PI lying around, so i can't really look deeper into the problem for now.

**Comment by peletiah** [comment]
Thanks! Yeah, probably reinstalling the plugin will work. Mostly I wanted to point this out in case someone stumbles over this problem and doesn't know how to fix it. I didn't really customize anything, it's largely a default osmc/kodi-installation.

So how are the dependencies like _python-simplejson_ defined in kodi? I assume the addons are not debian packages - is there a mechanism to integrate them in the package-manager, similar to a setup.py?

Thanks for your dedicated support!

**Comment by s0faking** [comment]
well afaik python modules are packaged into addons.  kodi fetches all modules defined in the addon.xml on install. in your case it kinda looks like kodi has skipped that step. Other osmc users are having the same problem: https://discourse.osmc.tv/t/after-kodi-17-update-no-module-named-simplejson/22193

did you update from an earlier osmc version or is this a fresh install?

**Comment by peletiah** [comment]
Ah, thanks a lot for the information! It's an old installation with regular updates.
