### ISSUE TITLE
BUNDESLAND HEUTE does not work inside "Sendungen"

### ISSUE THREAD

**Issue by typestar** [s0faking/plugin.video.orftvthek#5]
Dear s0faking,

thankyou for you latest fix, but unfortunately - I recognized this now - inside "Sendungen"
the "Bundesland heute"  does NOT work:  you cannot choose a different area, neither Vienna or any other austrian country...

Ich weiß nicht, woran es liegt, aber man kann kein Bundesland wählen und somit ist dieser Teil des Archivs defekt.
Thankyou for your work and efforts, again...!

typestar

**Comment by s0faking** [comment]
fixed the issue. just pushed the update. thx for the feedback

s0faking
