### ISSUE TITLE
Livestreams no longer working

### ISSUE THREAD

**Issue by Me4Linux** [s0faking/plugin.video.orftvthek#54]
Hi, s0faking,

the ORF live streams aren't working on both my Kodi installations (Kodi 17 on my x64 PC with Ubuntu 16.04 and on my smartphone with Android 6, ORF Plugin version 0.7.1). Also tried to switch to the ServiceAPI and changing stream quality but the live streams still don't play. The other non-live streams work without problems.

**Comment by s0faking** [comment]
check #52. the issue is already fixed. i also pushed the update to the offical repo. might take some time until its live.

**Comment by Me4Linux** [comment]
Sorry, didn't check the resolved issues before. Thank's for the quick reaction.
