### ISSUE TITLE
[0.8] no playback of content - livestream works fine

### ISSUE THREAD

**Issue by greg4b** [s0faking/plugin.video.orftvthek#61]
Thanks for your Addon!

But since 2 days I'm experiencing no playback of content. The items load fine, but no playback.

No errors shown - just no playback.

Livestream working fine.

Would be fine, if you could look into.

Danke,

Gregor

**Comment by s0faking** [comment]
hey greg4b,

thx for the issue. the orf servers blocked the kodi UA and therefore everyone ended up with an 403. i fixed the issue with 0.8.2.

https://github.com/s0faking/plugin.video.orftvthek/releases

cheers,
s0fa

**Comment by Rechi** [comment]
@s0faking don't forget to open a PR at https://github.com/xbmc/repo-plugins

**Comment by s0faking** [comment]
@Rechi i'm on it. just testing the release a little. looks like they got some performance problems with the orf servers. takes quite some time to load a show segment. probably the reason why they locked us out, in order to minimize the server load
