### ISSUE TITLE
Kodi crashes with the changes from PR #65 and #64

### ISSUE THREAD

**Issue by s0faking** [s0faking/plugin.video.orftvthek#66]
The "Play All" item doesnt work anymore with PR #65 and PR #64. Selecting "Play all" causes Kodi 17.6 to crash. this is happening with the serviceapi and htmlscraper setting. 
[kodi.log](https://github.com/s0faking/plugin.video.orftvthek/files/2091427/kodi.log)

**Comment by HiassofT** [comment]
Just tested current master (githash 7b7ae79, with the 2 PRs reverted) with current kodi master (commit https://github.com/xbmc/xbmc/commit/37f55e6bfd36a9cc550feaf5cffddc6c1f0a8862) on LibreELEC / RPi2 and "Play All" is still crashing kodi. orftvthek addon settings were all set to default.

Here's the crashlog: http://ix.io/1d2G

Backtrace and kodi log indicate the crash is related to the busy dialog, CGUIDialogBusy::WaitOnEvent occurs 2 times in the backtrace and the second invocation crashes

**Comment by s0faking** [comment]
@HiassofT is there a version of the addon which worked for you? i guess we can't consider 18.0-ALPHA2 as stable, so maybe this problem might go away when they release kodi 18.

**Comment by HiassofT** [comment]
@s0faking the addon was working fine on Kodi 18 until a couple of weeks ago and I used Play All very often for watching news (ZIB). If it helps you I could try earlier versions of the addon on earlier Kodi builds.

We've seen a lot of issues due to the busy dialog changes in the last month, and as the crash seems to be busy dialog related the question seems to be if it needs some fixing in the addon or in kodi - or both

**Comment by HiassofT** [comment]
I went back to older kodi versions. Most of May I was using a local LibreELEC build using kodi master from April 18th (commit https://github.com/xbmc/xbmc/commit/af4a5489295496d5f7dcabe097a263f08199494b).

On this kodi version addon 0.8.2 and current master version work fine, version 0.8.3 results in an endless spinner when using Play All.

I also tried a Milhouse builds from early May I had sitting on my harddrive, but there Play All just hung kodi - thats probably unrelated to the addon, the experimental reuse python PR that was included at that time caused a lot of trouble.

So I can't narrow down when exactly Play All broke, but I hope it helps a bit.

**Comment by Rechi** [comment]
The addon crashes Kodi since https://github.com/xbmc/xbmc/pull/13833, as marking an item as folder will cause a busy dialog (indicates waiting for items for a directory listing) and starting the video causes a second one (indicates buffering). So #64 and #65 are the correct fixes.

I don't know why that crashes v17 (and most likely also previous versions).

**Comment by HiassofT** [comment]
I did some more testing with 0.8.3 on current Kodi master, folder indeed seems to be set to false (AFAICT) but still kodi crashes.

During testing I also noticed that Kodi crashes when Playing a music folder (so no addon involved here).

Not sure if these crashes are related but I've opened a trac ticket: https://trac.kodi.tv/ticket/17915

**Comment by HiassofT** [comment]
@s0faking @Rechi @wsnipex could you enter the discussion at the trac ticket https://trac.kodi.tv/ticket/17915 ?

I traced version 0.8.2 of the addon and it looked like folder was set to false, i.e. the patches worked. Maybe I missed something though.

**Comment by s0faking** [comment]
thx  @HiassofT. will do

**Comment by s0faking** [comment]
@Rechi i cant seem to get this to work. i removed the playall listitem on the latest devel commit. for now only the autoplay option will open the playlist. did you have any breakthroughs on that issue? if we cant get this to work we should probably implement the autoplay option on the serviceapi scraper as well

**Comment by s0faking** [comment]
@Rechi  @HiassofT : i think i fixed the play all issue. can you test the last devel commit? works for me on 17.6 and e14a6f89-master-x64

**Comment by HiassofT** [comment]
Thanks! I tested with the devel branch (commit 1d635c7) and play all works fine, but with service api off and on
