### ISSUE TITLE
Video stuttering sometimes, but fine in browser

### ISSUE THREAD

**Issue by Schaussi** [s0faking/plugin.video.orftvthek#67]
Hi,
first of all a big thank you for this addon, it is very helpful.

What I noticed a few days ago (Austria - Brazil soccer game) was that the video stream was stuttering very often during the game. First I thought this would be an ORF bandwidth issue, but then noticed it was running fine on a Windows notebook with every browser.
Does the Tvthek maybe offer a newer/better streaming method than it is used in the Kodi addon?
Can some of the addon settings help in this case (ServiceAPI option, video quality option, ...)?
Which Kodi version do you recommend for the addon? I use 17.6, but would this addon use features like InputStream etc. with v18?

Thank you!

**Comment by s0faking** [comment]
Hi Schaussi,

you can try to use the serviceapi option. the htmlscraper uses a different playlist for the livestream (old ipad livestream url). maybe they limit the bandwidth on that. 

i recommend 17.6. You need to enable the adaptive stream addon to use the "Restart" option for livestreams, which works fine with kodi 17.6. havent tested much on kodi 18 tough

,s0fa

**Comment by Schaussi** [comment]
Perfect, thank you!
