### ISSUE TITLE
Feature request: Support for new UHD HEVC streams 

### ISSUE THREAD

**Issue by infinity85** [s0faking/plugin.video.orftvthek#69]
Hello,
since the soccer championship started, orf also offers uhd 4k and/also adaptive quality in their orf tvthek apps. As far as I see it in my Amazon Fire TV orf App, the old quality settings (same as in your addon) remain for h264 up to 720p with 24 frames. Then there is also an adaptive setting (also h264 up to 720 and max ~3,5mbit, 24fps) and then there is a New UHD quality setting:

This UHD setting is also adaptive and 50fps (ideal for soccer) and starts with 720p50 at ~7,5mbit, goes to 1080p50 at ~11mbit and should offer 2160p50 as well (cannot test, as no 4k tv here). But even for fullhd tvs it would be a huge benefit to make use of this uhd stream, as the 1080p50 picture is simply a huge step forward.

Would it be possible to add support for this new higher quality step? Only a few programs offer this uhd setting, I did see it only for the soccer matches so far. UHD is mentioned in the epg titles for these programs. 

My very best regards :)

**Comment by s0faking** [comment]
hi,

i think this already works with the serviceapi option by @Rechi. when i list the livestreams with the option enabled i can see [ORF1 UHD ...] Items, but the resoultion is still 720p. they might switch that tough when a game starts. 

as for the htmlscraper: i will add those options for the live streaming section

cheers,
s0fa

**Comment by Rechi** [comment]
I had a quick look and for serviceapi it should be a simple change, but with current code it won't work.

**Comment by infinity85** [comment]
@s0faking
Yep, it starts here with 720p50 as well, then climbs up to 1080p50 after 30s to 1 minute. It's adaptive, so it adjusts then to the given bandwidth. Cannot test 2160p uhd, as my tv is only an old fullhd one. 

@rechi
Sad to read it, though it might be something for the future :)

**Comment by Rechi** [comment]
@infinity85 can you try the following changes?
It will break everything else then WM livestream, just a quick workaround.
```--- a/resources/lib/serviceapi.py
+++ b/resources/lib/serviceapi.py
@@ -119,9 +119,9 @@ class serviceAPI(Scraper):

        def JSONStreamingURL(self,jsonVideos):
                source = None
-               if jsonVideos.get('progressive_download') != None:
-                       for streamingUrl in jsonVideos.get('progressive_download'):
-                               if streamingUrl.get('quality_key') == self.videoQuality:
+               if jsonVideos.get('hls') != None:
+                       for streamingUrl in jsonVideos.get('hls'):
+                               if streamingUrl.get('quality_key') == 'UHDBrowser':
                                        return generateAddonVideoUrl(streamingUrl.get('src'))
                                source = streamingUrl.get('src')

```

**Comment by s0faking** [comment]
@infinity85 please try the latest commit on the devel branch. i fixed the UHD stream for the htmlscraper and the adaptive quality setting should also work with both scrapers

**Comment by infinity85** [comment]
Hmmm... well, I'm not that good in debugging :/...

I tried at first the latest commit on the devel branch (downloaded an hour ago). The "Live" category doesn't work there comes an error (log snippet):
`19:07:31.991 T:3278226336   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.NameError'>
                                            Error Contents: global name 'child_restart' is not defined
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.orftvthek/default.py", line 153, in <module>
                                                scraper.getLiveStreams()
                                              File "/storage/.kodi/addons/plugin.video.orftvthek/resources/lib/htmlscraper.py", line 442, in getLiveStreams
                                                self.buildLivestream(child_list_title,child_list_link,child_list_time,data_sets,child_restart,channelnames,program,banner)
                                              File "/storage/.kodi/addons/plugin.video.orftvthek/resources/lib/htmlscraper.py", line 475, in buildLivestream
                                                if inputstreamAdaptive and child_restart:
                                            NameError: global name 'child_restart' is not defined
                                            -->End of Python script error report<--
19:07:32.179 T:4099792896   ERROR: GetDirectory - Error getting plugin://plugin.video.orftvthek/?link&mode=getLive
19:07:32.180 T:4099792896   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.orftvthek/?link&mode=getLive) failed
`
The other categories seem to work, but not as expected. Lets say I open "recent programs (or similar... do have it in german here), then the current Peru vs. Denmark match appears in the list. When I click on this line I expect the stream to start, but it opens some kind of sub-category instead. This contains some kind of chapters/footage of the actual match or so. All this is not UHD and not live unfortunately.

Then I tried to edit the serviceapi.py (devel branch) as described by @Rechi (I exchanged the original three lines with the new three ones), but it breaks a lot:
`19:01:42.678 T:3382367136   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndentationError'>
                                            Error Contents: ('expected an indented block', ('/storage/.kodi/addons/plugin.video.orftvthek/resources/lib/serviceapi.py', 123, 19, "                for streamingUrl in jsonVideos.get('hls'):\n"))
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.orftvthek/default.py", line 16, in <module>
                                                from resources.lib.serviceapi import *
                                            IndentationError: ('expected an indented block', ('/storage/.kodi/addons/plugin.video.orftvthek/resources/lib/serviceapi.py', 123, 19, "                for streamingUrl in jsonVideos.get('hls'):\n"))
                                            -->End of Python script error report<--
19:01:42.850 T:4099792896   ERROR: GetDirectory - Error getting plugin://plugin.video.orftvthek/
19:01:42.851 T:4099792896   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.orftvthek/) failed
19:03:42.386 T:3311813536   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndentationError'>
                                            Error Contents: ('expected an indented block', ('/storage/.kodi/addons/plugin.video.orftvthek/resources/lib/serviceapi.py', 123, 19, "                for streamingUrl in jsonVideos.get('hls'):\n"))
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.orftvthek/default.py", line 16, in <module>
                                                from resources.lib.serviceapi import *
                                            IndentationError: ('expected an indented block', ('/storage/.kodi/addons/plugin.video.orftvthek/resources/lib/serviceapi.py', 123, 19, "                for streamingUrl in jsonVideos.get('hls'):\n"))
                                            -->End of Python script error report<--
19:03:42.559 T:4099792896   ERROR: GetDirectory - Error getting plugin://plugin.video.orftvthek/
19:03:42.563 T:4099792896   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.orftvthek/) failed
19:03:45.539 T:3311813536   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndentationError'>
                                            Error Contents: ('expected an indented block', ('/storage/.kodi/addons/plugin.video.orftvthek/resources/lib/serviceapi.py', 123, 19, "                for streamingUrl in jsonVideos.get('hls'):\n"))
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.orftvthek/default.py", line 16, in <module>
                                                from resources.lib.serviceapi import *
                                            IndentationError: ('expected an indented block', ('/storage/.kodi/addons/plugin.video.orftvthek/resources/lib/serviceapi.py', 123, 19, "                for streamingUrl in jsonVideos.get('hls'):\n"))
                                            -->End of Python script error report<--
19:03:45.710 T:4099792896   ERROR: GetDirectory - Error getting plugin://plugin.video.orftvthek/
19:03:45.711 T:4099792896   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.orftvthek/) failed`

The addon is kind of broken afterwards.

I'm feeling a bit insecure whether I did the right things. For my understanding: How do I make sure that UHD stream (if available) is the first choice? I do not see any UHD setting anywhere. Also: If I compare the orftvthek app on my FireTV with this one, there seems to be no mentioning of UHD in the stream-titles shown by your addon. The orf app on my firetv has a "UHD" in the particular streams title... actually I see these "UHD" titles only at the titles of live matches.

**Comment by s0faking** [comment]
hey @infinity85 ,

thx for testing. i've fixed the error you described in your last post (child_restart missing ...). uhd with the htmlscraper should work now.

the uhd stream stutters on my desktop hardware too. i will try this on my shield tv tonight, but i guess this is not an addon bug.

regards,
s0fa

**Comment by s0faking** [comment]
@infinity85 
> Is there a way to force the adaptive uhd stream to choose 1080p50? 
yes this is already builtin in kodi. open the osd video settings and choose "select program". then you should see a list of qualities to choose from
