### ISSUE TITLE
HTML Scraper broken

### ISSUE THREAD

**Issue by s0faking** [s0faking/plugin.video.orftvthek#79]
The tvthek website layout changed. Use the ServiceAPI for now. I will try to adapt the html scraper asap

**Comment by tschoartschi** [comment]
Thank you for the info :-) ServiceAPI works for me but it's quite slow on my Raspi

**Comment by s0faking** [comment]
The htmlscraper is fixed with 0.9.0. I've already pushed the update to the official repo.
