### ISSUE TITLE
Plugin now unusable at RPi v1 (urllib changes)

### ISSUE THREAD

**Issue by killerbees19** [s0faking/plugin.video.orftvthek#81]
The latest release (0.9.0) is nearly unusable at Raspberry Pi's from the first generation. I manage two devices with old OSMC installations and traced this down to this commit: https://github.com/s0faking/plugin.video.orftvthek/commit/e1044e856ffd05cba5e28644731368379ddf9234

Without this commit everything is fine again. I've build a test version with reverted commit here: https://github.com/froonix/plugin.video.orftvthek/commits/debug-20190411

Problem description: It takes more than 3 minutes to load a single menu (like "Sendungen") with v0.9.0! There's no suspicious log entry, no OOM situation, just high CPU load. Without the mentioned commit it takes only 15-35 seconds at the first run. Not perfect, but that's the usual Python performance with OSMC at the RPi v1… 🤣

I'm not a Python programmer or user, I don't know what's the big difference at the recent urllib changes.

_Edit: I'm using the Service API btw. Not the HTML scraper._

_Related: #78_

**Comment by s0faking** [comment]
Python3 performs slower than Python2(afaik). KODI is forcing a Python3 compatibility now, so i can't really undo those changes on the addon. How is the performance with the HTML scraper?

**Comment by killerbees19** [comment]
Sorry for the delay! I'll test the HTML scraper next week(end), I'm currently not at the location with the RPi v1.

I understand that you can't revert the changes. Maybe the best solution would be, that I'll backport all important new commits into a dedicated branch at my repository. I've already upgraded one location to a RPi 3B+, but that's not possible for all locations.

**Comment by killerbees19** [comment]
I'll upgrade the last RPi v1 location next weekend to RPi v3 :-)

/closed
