### ISSUE TITLE
serviceAPI: slow response parsing (livestream ~90s on RPi2)

### ISSUE THREAD

**Issue by haubi** [s0faking/plugin.video.orftvthek#83]
On the Raspberry Pi 2, opening the list of live streams takes ~90s (measured).
It turns out that in `serviceAPI.getLiveStreams()`, `__makeRequest` takes ~3s only.
It is the `json.loads(response.read().decode('UTF-8')).get('_embedded').get('items')` taking ~80s before the first `result` item is iterated in the loop.

A workaround is in the `__urlLive` to reduce the `limit` from `1000` to something like `10` or `20`, because 1000 entries in the live stream list do not make so much sense anyway IMHO.
Otherways, I have no idea on how to improve parsing speed itself.

**Comment by s0faking** [comment]
Please try 0.9.1. i reduced the GET Parameter to 20. i also changed the listing for livestreams. now only one item per channel is shown because i removed the schedules livestream start feature.

**Comment by haubi** [comment]
Thanks, the limit of 20 provides a delay of ~15 seconds, which (could be better but) is acceptable.

The "one item per channel" change may not work as expected, because it still does show items not started yet. For example, any "AD" is a separate channel, so I can see the "ORF 1 (AD) at 20:15" item already, because the current "ORF 1 at 19:53" item does not have an AD part.

But while I do understand the idea for "one item per channel", I do like to see all the upcoming items (up to above limit of 20), even if there is no scheduled start feature (this has never worked here anyway), because: When I can see the 20:15 item for ORF 1 I'd like to watch, I can start the current ORF 1 item right now (at ~20:00 for example).

**Comment by s0faking** [comment]
with 0.10.0 you can enable the schedule view if you are using the serviceapi. the option is called "Show Full Livestream Schedule". the new limit is also implemented on this version

**Comment by haubi** [comment]
Nice, thanks!
