### ISSUE TITLE
Videostream Radiokulturhaus

### ISSUE THREAD

**Issue by polojoe** [s0faking/plugin.video.orftvthek#84]
Could you add the live stream of the Radiokulturhaus to the addon?
EG today there is a very good concert of Federspiel.
https://radiokulturhaus.orf.at/

**Comment by s0faking** [comment]
this is not a regular livestream. also i don't think its a good idea to add other orf services (not tvthek content) to the addon. There might me an easy way to watch the livestreams from Radiokulturhaus on Kodi anyway. can't really verify that though unless i got a look at the livestream when it's happening.
