### ISSUE TITLE
opening any item doesn't show anything

### ISSUE THREAD

**Issue by filipppp** [s0faking/plugin.video.orftvthek#85]
Installed on Libreelec Jarvis and using latest plugin version.

When opening any item (Shows, Live..) just the ".." item for going back is shown in the result list.

**Comment by s0faking** [comment]
this might be caused by a network error on your side or a network error on the orf server side. are you still getting the same error. just tested on win and everything looks fine here

**Comment by filipppp** [comment]
Still getting the same error, can't be because of my network since I can watch a livestream in the background. Any ideas?

**Comment by s0faking** [comment]
just tested the addon on 16.1 (win). works fine here. could you please supply debug log files for the error and a short description of your current addon settings. have you tried uninstalling and reinstalling the addon from the official repo? 0.9.0 should definitely work

**Comment by s0faking** [comment]
i was able to reproduce the issue on the live stream listitem. it looks like the orf tvthek website has an additional teaser element which breaks my scraper routine. i will get back to you as soon as i got a fix

**Comment by filipppp** [comment]
Reinstalling the addon didn't help, where are the log files you need?

**Comment by s0faking** [comment]
no worries. i found the cause of the error. no need to hassle with the log files

**Comment by s0faking** [comment]
alright, i checked my hint but it looks like that wasn't it. can you send me some logfiles? you can find the steps on how to get those files here: https://kodi.wiki/view/Log_file/Easy

just to rule one thing out: do you have "all videos" enabled in your kodi view? if you just enabled "unwatched videos", livestreams you already watched are not shown

**Comment by s0faking** [comment]
any progress on this issue?

**Comment by filipppp** [comment]
Sorry, I totally forgot. I will look into it tomorrow.

**Comment by luchmhor** [comment]
Hello. Maybe I can help here; I'm using osmc developing branch and I guess the problem is due to changes in latest kodi:

The discussion on osmc is here:

https://discourse.osmc.tv/t/kodi-19-matrix-nightly-builds-for-vero-2-4k/79408/79?u=luchmhor

the logs are here:

https://paste.osmc.tv/yimeyeqajo

The plugin (better ffmpeg) throws a 403 http error. Which is very awkward:
```
2019-07-25 22:37:36.090 T:3527369440    INFO: ffmpeg[0xafb1d5c0X]: [hls,applehttp] Opening 'http://varorfvod.sf.apa.at/cms-worldwide_nas/_definst_/nas/cms-worldwide/online/2019-07-25_2200_tl_02_ZIB-2_Signation---The__14020907__o__460581745d__s14533775_5__ORF2HD_22001614P_22010620P.smil/chunklist_b992000.m3u8?lbs=20190725223736856&origin=http%253a%252f%252fvarorfvod.sf.apa.at%252fcms-worldwide_nas%252f_definst_%252fnas%252fcms-worldwide%252fonline%252f2019-07-25_2200_tl_02_ZIB-2_Signation---The__14020907__o__460581745d__s14533775_5__ORF2HD_22001614P_22010620P.smil%252fchunklist_b992000.m3u8&ip=185.17.13.235&ua=Mozilla%252f5.0%2b(Windows%2bNT%2b10.0%253b%2bWin64%253b%2bx64)%2bAppleWebKit%252f537.36%2b(KHTML%252c%2blike%2bGecko)%2bChrome%252f65.0.3325.181%2bSafari%252f537.36' for reading
2019-07-25 22:37:36.113 T:3527369440   DEBUG: ffmpeg[0xafb1d5c0X]: [http] HTTP error 403 Access denied.
```

**Comment by s0faking** [comment]
is this still an issue?

**Comment by filipppp** [comment]
Not using Kodi anymore, so can't check, sorry for trafficing this issue like that.

**Comment by filipppp** [comment]
Okay, I still need it tho, any way to debug?

**Comment by s0faking** [comment]
> just to rule one thing out: do you have "all videos" enabled in your kodi view? if you just enabled "unwatched videos", livestreams you already watched are not shown

did you check that? 

are you using 0.9.1 now? can you enable the curl "component specific" debug log and post the log here. does the same thing happen with the service api enabled?

**Comment by filipppp** [comment]
I'm using 0.9.0, there isn't a newer version in the repo. Yes I did check for "unwatched videos", that's not the issue.


Yes I will post the log tomorrow then. What is the service API?

**Comment by s0faking** [comment]
its another way to fetch the tvthek data (json api). according to the log you are using the html scraper. you can change that in the addon settings

**Comment by filipppp** [comment]
When enabling the service API it works, but it's really slow when loading

**Comment by s0faking** [comment]
closed due to inactivity
