### ISSUE TITLE
adding favourite results in a not refreshed content link

### ISSUE THREAD

**Issue by AloisKlingler** [s0faking/plugin.video.orftvthek#90]
hi,

I am using the most current tvthek plugin on a recent OSMC.
I do not use the serviceapi as in case I switch it on all entries in a "Sendung" is named without date. So, e.g. if I go to Sendungen -> ZIB" all entries listed in are only called "ZIB" while without the serviceapi they are listed by date in there.

But, I am struggling after reinstalling OSMC and setting all up from scratch. I like to create favourites but the content of these created favourites are never refreshed any more.

E.g. I go to "Sendungen" -> "ZIB" and create a Favourite, on visiting this Favourite tomorrow it will only show the content from today (or from the day where I created the favourite).

As this was not the case on my old OSMC installation I restored the favourites.xml - and with the old xml the favourite is working again.

I remember, I had this issue already 2 or 3 years ago and just was happy the links were working suddenly. so, it still should be possible to create working favourites, but I do not know how.

my not working favourites´(newly created):
`    <favourite name="ORF Live" thumb="/home/osmc/.kodi/addons/plugin.video.orftvthek/resources/media/live_banner_v2.jpg">ActivateWindow(10025,&quot;plugin://plugin.video.orftvthek/?link&amp;mode=getLive&quot;,return)</favourite>
    <favourite name="ZIB 1" thumb="https://api-tvthek.orf.at/uploads/media/profiles/0081/16/thumb_8015010_profiles_player.jpeg">ActivateWindow(10025,&quot;plugin://plugin.video.orftvthek/?banner=https%3a%2f%2fapi-tvthek.orf.at%2fuploads%2fmedia%2fprofiles%2f0081%2f16%2fthumb_8015010_profiles_player.jpeg&amp;link=https%3a%2f%2ftvthek.orf.at%2fprofile%2fZIB-1%2f1203%2fZIB-1%2f14031326&amp;mode=getSendungenDetail&quot;,return)</favourite>
    <favourite name="Wetter ZIB" thumb="https://api-tvthek.orf.at/uploads/media/profiles/0001/14/thumb_13051_profiles_player.jpeg">ActivateWindow(10025,&quot;plugin://plugin.video.orftvthek/?banner=https%3a%2f%2fapi-tvthek.orf.at%2fuploads%2fmedia%2fprofiles%2f0001%2f14%2fthumb_13051_profiles_player.jpeg&amp;link=https%3a%2f%2ftvthek.orf.at%2fprofile%2fWETTER-ZIB%2f1171769%2fWetter%2f14031327&amp;mode=getSendungenDetail&quot;,return)</favourite>
    <favourite name="Tirol heute" thumb="https://api-tvthek.orf.at/uploads/media/profiles/0026/99/thumb_2598844_profiles_player.jpeg">ActivateWindow(10025,&quot;plugin://plugin.video.orftvthek/?banner=https%3a%2f%2fapi-tvthek.orf.at%2fuploads%2fmedia%2fprofiles%2f0026%2f99%2fthumb_2598844_profiles_player.jpeg&amp;link=https%3a%2f%2ftvthek.orf.at%2fprofile%2fTirol-heute%2f70023%2fTirol-heute%2f14031383&amp;mode=getSendungenDetail&quot;,return)</favourite>
    <favourite name="Wetter Tirol" thumb="https://api-tvthek.orf.at/uploads/media/profiles/0028/73/thumb_2772597_profiles_player.jpeg">ActivateWindow(10025,&quot;plugin://plugin.video.orftvthek/?banner=https%3a%2f%2fapi-tvthek.orf.at%2fuploads%2fmedia%2fprofiles%2f0028%2f73%2fthumb_2772597_profiles_player.jpeg&amp;link=https%3a%2f%2ftvthek.orf.at%2fprofile%2fWetter-Tirol%2f8094993%2fWetter-Tirol%2f14031386&amp;mode=getSendungenDetail&quot;,return)</favourite>
</favourites>`

my working favourites (exported from the old OSMC SD-card)
`<favourites>
    <favourite name="ORF Live" thumb="/home/osmc/.kodi/addons/plugin.video.orftvthek/resources/media/live_banner.jpg">ActivateWindow(10025,&quot;plugin://plugin.video.orftvthek/?banner=%2fhome%2fosmc%2f.kodi%2faddons%2fplugin.video.orftvthek%2fresources%2fmedia%2flive_banner.jpg&amp;link&amp;mode=getLive&amp;title=Live&quot;,return)</favourite>
    <favourite name="ZIB 1" thumb="http://api-tvthek.orf.at/uploads/media/profiles/0001/14/thumb_13001_profiles_list.jpeg">ActivateWindow(10025,&quot;plugin://plugin.video.orftvthek/?banner=http%3a%2f%2fapi-tvthek.orf.at%2fuploads%2fmedia%2fprofiles%2f0001%2f14%2fthumb_13001_profiles_list.jpeg&amp;link=http%3a%2f%2ftvthek.orf.at%2fprofile%2fZIB-1%2f1203&amp;mode=getSendungenDetail&amp;title=ZIB%201&quot;,return)</favourite>
    <favourite name="WETTER ZIB" thumb="http://api-tvthek.orf.at/uploads/media/profiles/0001/14/thumb_13051_profiles_list.jpeg">ActivateWindow(10025,&quot;plugin://plugin.video.orftvthek/?banner=http%3a%2f%2fapi-tvthek.orf.at%2fuploads%2fmedia%2fprofiles%2f0001%2f14%2fthumb_13051_profiles_list.jpeg&amp;link=http%3a%2f%2ftvthek.orf.at%2fprofile%2fWETTER-ZIB%2f1171769&amp;mode=getSendungenDetail&amp;title=WETTER%20ZIB&quot;,return)</favourite>
    <favourite name="Tirol heute" thumb="http://api-tvthek.orf.at/uploads/media/profiles/0001/14/thumb_13032_profiles_list.jpeg">ActivateWindow(10025,&quot;plugin://plugin.video.orftvthek/?banner=http%3a%2f%2fapi-tvthek.orf.at%2fuploads%2fmedia%2fprofiles%2f0001%2f14%2fthumb_13032_profiles_list.jpeg&amp;link=http%3a%2f%2ftvthek.orf.at%2fprofile%2fTirol-heute%2f70023&amp;mode=getSendungenDetail&amp;title=Tirol%20heute&quot;,return)</favourite>
    <favourite name="Wetter Tirol" thumb="http://api-tvthek.orf.at/uploads/media/profiles/0001/14/thumb_13147_profiles_list.jpeg">ActivateWindow(10025,&quot;plugin://plugin.video.orftvthek/?banner=http%3a%2f%2fapi-tvthek.orf.at%2fuploads%2fmedia%2fprofiles%2f0001%2f14%2fthumb_13147_profiles_list.jpeg&amp;link=http%3a%2f%2ftvthek.orf.at%2fprofile%2fWetter-Tirol%2f8094993&amp;mode=getSendungenDetail&amp;title=Wetter%20Tirol&quot;,return)</favourite>
</favourites>`

you can copy and paste (after terminating kodi) these lines to /home/osmc/.kodi/userdata/favourites.xml so you should be able to reproduce easily. :-)

thanks for your efforts.

Best regards
Alois

**Comment by s0faking** [comment]
i tried to create a fix for this. the problem was that the tvthek links the last show as the main show url on the overview. if you add those to the favourites the old show is linked (until it is taken offline i guess). not sure if the url pattern i guessed is consistent, but it seems to work for the few shows i've tested so far. i've pushed this to the python3 branch for now because i'm working on an update to make the addon kodi19 compatible.

**Comment by s0faking** [comment]
this should be fixed with 0.10.0

**Comment by AloisKlingler** [comment]
Hi,

Thank you, will check and report back if it does not work with 0.10. :-)

Best regards
