### ISSUE TITLE
xbmc.python 3.0 ABI compatibility

### ISSUE THREAD

**Issue by raoulbhatia** [s0faking/plugin.video.orftvthek#96]
March test builds of Kodi and LibreELEC enforce xbmc.python 3.0 ABI compatibility, see
* https://github.com/xbmc/xbmc/pull/17188
* https://forum.kodi.tv/showthread.php?tid=343068&pid=2928509#pid2928509
* https://github.com/s0faking/plugin.video.orftvthek/blob/master/addon.xml#L4

It would be awesome if you can check addon would be checked for compatibility.
(I am currently on an earlier test build due to other reasons, but would love to follow the nightly builds again soon).

**Comment by raoulbhatia** [comment]
I tried to check myself but am not knowledgeable enough to move this forward.

I followed the change in https://github.com/xbmc/xbmc/pull/16121 in `createListItem`, see https://github.com/s0faking/plugin.video.orftvthek/blob/master/resources/lib/base.py#L54

This allowed me to start the plugin again.  However, when trying to play an item, i get

```
2020-05-11 22:28:43.208 T:2319     INFO <general>: initializing python engine.
2020-05-11 22:28:45.253 T:2319     INFO <general>: CPythonInvoker(12, /storage/.kodi/addons/plugin.video.orftvthek/default.py): script successfully run
2020-05-11 22:28:45.294 T:2318     INFO <general>: easy_acquire - Created session to https://api-tvthek.orf.at
2020-05-11 22:28:45.660 T:2319  WARNING <general>: CPythonInvoker(12, /storage/.kodi/addons/plugin.video.orftvthek/default.py): the python script "/storage/.kodi/addons/plugin.video.orftvthek/default.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE,N9XBMCAddon4xbmc8PlayListE,N9XBMCAddon4xbmc6PlayerE
2020-05-11 22:28:45.660 T:2319     INFO <general>: Python interpreter stopped
```

Let me know if I can provide further details.  I'd love to get the ORF TVhhek back on my Kodi ❤️

Raoul

**Comment by s0faking** [comment]
Sorry for the late reply. I guess this one slipped through. Well the problem with this is that i can't up the API Version without cutting people off with older Kodi versions. As for the problem with the "createListItem", i will have to check if the functions from the github page you posted are supported on older kodi versions as well. Can i ask why you are using Nightly Builds in production?

**Comment by raoulbhatia** [comment]
FYI with the patches I did I was able to watch ORF again after a reboot.  As I am not watching ORF frequently, I do not know if this is working w/o issues.

As for the build I am using: I am also a Prime VOD user and playback frequently broke when using stable releases.  The only way I was able to get Prime VOD to work again was by using the nightly Milhouse LibreELEC builds.

Raoul

**Comment by luchmhor** [comment]
Can you apply these changes in e.g. the devel branch and people who are on kodi bleeding edge will be able to fetch the plugin from there?

**Comment by s0faking** [comment]
https://github.com/s0faking/plugin.video.orftvthek/commit/afcfeadc4f5d483667cbc63c1fb418aebda652df

i tested this on a nightly kodi on windows but i guess this will be fine on libreelec too

**Comment by luchmhor** [comment]
thx, works very well.

**Comment by s0faking** [comment]
added to kodi v19 repo. the code changes are sitting on the devel branch for now
