### ISSUE TITLE
[Bug] Service API not working with Livestream

### ISSUE THREAD

**Issue by flashkiller999** [s0faking/plugin.video.orftvthek#99]
**Hardware:**
Raspberry Pi 4 (4GB)
**Software:**
Libreelec 10
Kodi 19 (Matrix)
Plugin Version: 0.11.0

**Reproduction:**
Enable "Use ServiceAPI" in Addon Settings
Open Addon and select "Livestream"

**Expected behaviour:**
Listing of current Livestreaming channels

**Errorlog:**
> 2021-03-25 15:10:41.822 T:1578    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: append() takes exactly one argument (2 given)
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.orftvthek/default.py", line 6, in <module>
                                                       Addon.run()
                                                     File "/storage/.kodi/addons/plugin.video.orftvthek/resources/lib/Addon.py", line 137, in run
                                                       scraper.getLiveStreams()
                                                     File "/storage/.kodi/addons/plugin.video.orftvthek/resources/lib/ServiceApi.py", line 304, in getLiveStreams
                                                       contextMenuItems.append(self.translation(30063), 'RunPlugin(plugin://%s/?mode=liveStreamRestart&link=%s)' % (xbmcaddon.Addon().getAddonInfo('id'), result.get('id')))
                                                   TypeError: append() takes exactly one argument (2 given)
                                                   -->End of Python script error report<--

**Comment by s0faking** [comment]
this has already been reported and fixed with isssue #98. the update hasnt been pushed to the kodi repo yet. use 0.10.3 from the releases page for now
